AWSTemplateFormatVersion: "2010-09-09"
Description: 'Do something e.g. <env>.blah.net'
Resources:
  AnyResource:
    Type: AWS::EC2::VPC
    Properties:
      EnableDnsSupport: true
      EnableDnsHostnames: true
      CidrBlock: "100.0.0/20"
